"""Descent via a rational 2-isogeny.

Setting
-------
E  : y^2 = x (x^2 + a x + b)                    with the 2-torsion point T=(0,0)
E' : y^2 = x (x^2 - 2a x + (a^2 - 4b))          = E / <T>
phi : E -> E' the quotient isogeny, phihat : E' -> E its dual, phihat.phi = [2].

The descent map is
        alpha : E(Q) -> Q*/(Q*)^2 ,   O -> 1,  (0,0) -> b,  (x,y) -> x
and it is a group homomorphism with kernel exactly phihat(E'(Q)).  Likewise
alpha' on E'.  From 0 -> E'/phi -> E/2E -> ... one gets the exact counting
identity

        2^rank(E) = |Im alpha| * |Im alpha'| / 4.                     (*)

Everything the tool claims comes from bracketing the two unknown groups:

        <classes realised by points>  <=  Im alpha  <=  Selmer group.

The left bracket is proved by exhibiting rational points.  The right bracket
is proved by local obstructions.  Both are unconditional.  Ш never enters as
an assumption: it is precisely the gap between the two brackets, and when the
brackets touch, the gap is *proved* to be trivial rather than assumed to be.

Where the classes live
----------------------
If (x,y) is on E with x != 0, write x = m/n^2 in lowest terms; then
m * (m^2 + a m n^2 + b n^4) is a square, and any common factor of the two
factors divides b.  Hence the squarefree part of x divides b: the candidate
set is finite and explicit.

The homogeneous space
---------------------
alpha(P) = d means x = d T^2 for some rational T.  Substituting into
y^2 = x(x^2+ax+b) and putting W = y/(dT) gives

        C_d :  W^2 = d T^4 + a T^2 + (b/d),

a genus-one curve with a rational point exactly when d is in Im alpha.
Homogenising T = u/v, W = w/v^2:  w^2 = d u^4 + a u^2 v^2 + e v^4, e = b/d.
Back-map:  x = d u^2 / v^2 ,  y = d u w / v^3.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fractions import Fraction as F
from math import gcd

from .arith import sqrt_exact, squarefree_divisors, squarefree_part
from .curve import DescentModel, O, Point
from .local import everywhere_locally_soluble

# ------------------------------------------------- Q*/(Q*)^2 as squarefrees --


def sf(n) -> int:
    """Class of a nonzero rational in Q*/(Q*)^2, as a squarefree integer."""
    if hasattr(n, "numerator"):
        return squarefree_part(n.numerator * n.denominator)
    return squarefree_part(n)


def sf_mul(x: int, y: int) -> int:
    return squarefree_part(x * y)


def subgroup_generated(gens) -> list[int]:
    """The subgroup of Q*/(Q*)^2 generated by the given classes."""
    S = {1}
    for g in gens:
        g = sf(g)
        if g == 0:
            continue
        while True:
            new = {sf_mul(s, t) for s in S for t in S | {g}}
            if new <= S:
                break
            S |= new
    return sorted(S)


def is_subgroup(S) -> bool:
    Ss = set(S)
    if 1 not in Ss:
        return False
    return all(sf_mul(x, y) in Ss for x in Ss for y in Ss)


# ------------------------------------------------------------ point search --


def search_homogeneous_space(d: int, a: int, e: int, bound: int, start: int = 1):
    """Look for a rational point on C_d : w^2 = d u^4 + a u^2 v^2 + e v^4.

    Exhaustive over coprime (u, v) with 0 <= u <= bound, start <= v <= bound.
    A hit is a *proof* that d lies in Im alpha; a miss proves nothing, which is
    exactly why the tool never reports a rank from a miss.
    """
    for v in range(start, bound + 1):
        v2 = v * v
        v4 = v2 * v2
        ev4 = e * v4
        av2 = a * v2
        for u in range(0, bound + 1):
            if gcd(u, v) != 1:
                continue
            u2 = u * u
            val = d * u2 * u2 + av2 * u2 + ev4
            if val < 0:
                continue
            w = sqrt_exact(val)
            if w is not None:
                return (u, v, w)
    return None


def point_from_space(d: int, u: int, v: int, w: int) -> Point:
    """(u,v,w) on C_d  ->  the corresponding point of E(Q)."""
    if v == 0:
        return O
    x = F(d * u * u, v * v)
    y = F(d * u * w, v ** 3)
    return Point(x, y)


# ------------------------------------------------------------- the descent --


@dataclass
class SideResult:
    """One side of the descent (either E with alpha, or E' with alpha')."""

    a: int
    b: int
    candidates: list[int] = field(default_factory=list)
    selmer: list[int] = field(default_factory=list)
    realised: list[int] = field(default_factory=list)  # subgroup generated
    points: dict = field(default_factory=dict)  # class -> Point on this model
    obstructions: dict = field(default_factory=dict)  # class -> place
    local_certain: bool = True

    @property
    def dim_selmer(self) -> int:
        return (len(self.selmer)).bit_length() - 1

    @property
    def dim_realised(self) -> int:
        return (len(self.realised)).bit_length() - 1

    @property
    def sharp(self) -> bool:
        return len(self.selmer) == len(self.realised)


def descend_one_side(a: int, b: int, search_bounds=(60, 250, 900)) -> SideResult:
    """Compute Selmer group and realised subgroup for y^2 = x(x^2+ax+b)."""
    res = SideResult(a=a, b=b)
    res.candidates = squarefree_divisors(b)

    # ---- upper bracket: the Selmer group (local solubility everywhere) ----
    sel = []
    for d in res.candidates:
        if b % d != 0:
            continue
        e = b // d
        ok, certain, wit = everywhere_locally_soluble(d, a, e)
        res.local_certain = res.local_certain and certain
        if ok:
            sel.append(d)
        else:
            res.obstructions[d] = wit["obstruction"]
    res.selmer = sorted(sel)

    # Self-check.  The Selmer group is a *group*: it is the preimage of a
    # subgroup under a homomorphism.  If the local tests were buggy the set
    # would generically fail to be closed under multiplication, so this is a
    # real test of the p-adic engine, not a tautology.
    if res.local_certain and not is_subgroup(res.selmer):
        raise AssertionError(
            f"Selmer set {res.selmer} for y^2=x(x^2+{a}x+{b}) is not a subgroup "
            "of Q*/(Q*)^2 -- local solubility engine is wrong"
        )

    # ---- lower bracket: classes realised by honest rational points --------
    # (0,0) is always rational and alpha((0,0)) = b.
    known = {1: O}
    b_sf = sf(b)
    if b_sf != 1:
        known[b_sf] = Point(0, 0)
    G = subgroup_generated(list(known))

    for bound in search_bounds:
        if len(G) == len(res.selmer):
            break
        for d in res.selmer:
            if d in G:
                continue
            e = b // d
            hit = search_homogeneous_space(d, a, e, bound)
            if hit is not None:
                u, v, w = hit
                known[d] = point_from_space(d, u, v, w)
                G = subgroup_generated(list(known) + list(G))
        G = subgroup_generated(list(known) + list(G))

    # Self-check.  Every class realised by an honest rational point must be
    # locally soluble everywhere.  A violation means either the point search
    # produced a non-point or a local test wrongly said "insoluble" -- the one
    # kind of error that could inflate a claimed rank.
    for d in G:
        if res.local_certain and d not in res.selmer:
            raise AssertionError(
                f"class {d} realised by a rational point but declared locally "
                f"insoluble for y^2=x(x^2+{a}x+{b}) -- descent engine is wrong"
            )
    for d, P in known.items():
        if not res_curve_contains(a, b, P):
            raise AssertionError(f"search returned a non-point {P} for class {d}")

    res.realised = G
    res.points = known
    return res


def res_curve_contains(a: int, b: int, P: Point) -> bool:
    if P.inf:
        return True
    x, y = P.x, P.y
    return y * y == x * (x * x + a * x + b)


@dataclass
class DescentResult:
    model: DescentModel
    side: SideResult
    side_prime: SideResult

    @property
    def rank_upper(self) -> int:
        return self.side.dim_selmer + self.side_prime.dim_selmer - 2

    @property
    def rank_lower(self) -> int:
        return self.side.dim_realised + self.side_prime.dim_realised - 2

    @property
    def certified(self) -> bool:
        return self.rank_upper == self.rank_lower

    @property
    def local_certain(self) -> bool:
        return self.side.local_certain and self.side_prime.local_certain

    @property
    def sha_phi_dim(self) -> int:
        """dim_F2 Ш(E/Q)[phi] -- only meaningful once the descent is sharp."""
        return self.side.dim_selmer - self.side.dim_realised

    @property
    def sha_phihat_dim(self) -> int:
        return self.side_prime.dim_selmer - self.side_prime.dim_realised


def two_isogeny_descent(model: DescentModel, search_bounds=(60, 250, 900)) -> DescentResult:
    Ep = model.isogenous()
    s = descend_one_side(model.a, model.b, search_bounds)
    sp = descend_one_side(Ep.a, Ep.b, search_bounds)
    return DescentResult(model=model, side=s, side_prime=sp)
